remote_theme: sophiware/just-the-docs
logo: /assets/images/mini-banner.png
search_enabled: true
aux_links:
  "Stagync on GitHub":
    - "//github.com/sophiware/stagync"
color_scheme: yellow
paginate: 5
paginate_path: "/blog/page:num/"
